name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["new-branch"]

env:
  AZURE_FUNCTIONAPP_NAME: 'bot_raskhody'  # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Path to the python version you use
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
